song_list = [
    "https://www.youtube.com/watch?v=NaREybZM2SU",  # Iwami Takeshi - anoko dokonoko
    "https://www.youtube.com/watch?v=RvWbcK3YQ_o",  # Architects - Doomsday
    "https://www.youtube.com/watch?v=fLeFnN5tarI",  # Mitsukiyo - Bunny Bunny Carrot Carrot
    "https://www.youtube.com/watch?v=vl3L8TxaTU0",  # Death Grips - Death Grips is Online
    "https://www.youtube.com/watch?v=RerFq9IdOcg",  # Hakushi Hasegawa - Doku
    "https://www.youtube.com/watch?v=7-kU8zW6FMo",  # Porter Robinson - Get Your Wish (Sewerslvt Remix)
    "https://www.youtube.com/watch?v=9gVhtz7uuWk",  # underscores - Good luck final girl
    "https://www.youtube.com/watch?v=PkzVrZPgAKE",  # Tree Palm - Her Name Is ユビンLady
    "https://www.youtube.com/watch?v=NOm44l-RUk8",  # Hakushi Hasegawa - Itsukushii Hibi
    "https://www.youtube.com/watch?v=EtzjCmKho3w",  # MEMODEMO - Memento
    "https://www.youtube.com/watch?v=jxtWIwkBLMI",  # KINEMA106 - N.M.W
    "https://www.youtube.com/watch?v=QxKG2lUfTRE",  # POLKADOT STINGRAY - Otoshimae
    "https://www.youtube.com/watch?v=8pwGYLwTMhk",  # quannnic - snarky
    "https://www.youtube.com/watch?v=XsG2y5_MRDQ",  # halca - Toki toshite Violence
    "https://www.youtube.com/watch?v=CIFTPU3Ex2g",  # Good Kid - Witches
    "https://www.youtube.com/watch?v=uZdnPgDaOpk",  # inabakumori - Yokuyoku
    "https://www.youtube.com/watch?v=aGKLO876Kn4",  # 波姉利璃兎 - 恋?で愛?で暴君です!
    "https://www.youtube.com/watch?v=m6ysCZQm6Jc",  # RubberBand - 每道微小
]